// Generated by gencpp from file melissa_services/WordCount.msg
// DO NOT EDIT!


#ifndef MELISSA_SERVICES_MESSAGE_WORDCOUNT_H
#define MELISSA_SERVICES_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <melissa_services/WordCountRequest.h>
#include <melissa_services/WordCountResponse.h>


namespace melissa_services
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace melissa_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melissa_services::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::melissa_services::WordCount&) { return value(); }
};

template<>
struct DataType< ::melissa_services::WordCount > {
  static const char* value()
  {
    return "melissa_services/WordCount";
  }

  static const char* value(const ::melissa_services::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::melissa_services::WordCountRequest> should match
// service_traits::MD5Sum< ::melissa_services::WordCount >
template<>
struct MD5Sum< ::melissa_services::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melissa_services::WordCount >::value();
  }
  static const char* value(const ::melissa_services::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melissa_services::WordCountRequest> should match
// service_traits::DataType< ::melissa_services::WordCount >
template<>
struct DataType< ::melissa_services::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::melissa_services::WordCount >::value();
  }
  static const char* value(const ::melissa_services::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melissa_services::WordCountResponse> should match
// service_traits::MD5Sum< ::melissa_services::WordCount >
template<>
struct MD5Sum< ::melissa_services::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melissa_services::WordCount >::value();
  }
  static const char* value(const ::melissa_services::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melissa_services::WordCountResponse> should match
// service_traits::DataType< ::melissa_services::WordCount >
template<>
struct DataType< ::melissa_services::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::melissa_services::WordCount >::value();
  }
  static const char* value(const ::melissa_services::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELISSA_SERVICES_MESSAGE_WORDCOUNT_H
